version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: unless-stopped

  # Redis кэш
  redis:
    image: redis:8.0-alpine
    container_name: redis_cache
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app_network
    restart: unless-stopped

  # PHP-FPM
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php_app
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis_cache
    volumes:
      - ./src:/var/www/html
    networks:
      - app_network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - app_network
    depends_on:
      - php
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge